### ISSUE TITLE
Canvas XML Namespace Issue

### ISSUE THREAD

**Issue by emandres** [LtiLibrary/LtiLibrary#1]
We're running through Instructure's Canvas Dev course (https://canvas.instructure.com/courses/785215) and noticed that the outcome service response in the course uses the xml namespace from the 1.1 draft spec (http://www.imsglobal.org/lis/oms1p0/pox) but LtiLibrary uses the one from the 1.1.1 final spec (http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0). We understand that Canvas is using an outdated namespace but it would be nice if the library accepted either.

**Comment by andyfmiller** [comment]
That's a great course! I just pointed someone to it yesterday.

I'm using .NET's built in XmlSerializer functionality, including using xsd.exe to generate a serializer (OMSv1p0_LTIv1p1Profile_SyncXSD_v1p0.cs). That's where the most recent namespace is captured. For example,

'
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(TypeName="imsx_CodeMajor.Type", Namespace="http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0")]
    [XmlRoot("imsx_codeMajor", Namespace="http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0", IsNullable=false)]
    public enum imsx_CodeMajorType {
'

How do I accept either namespace?
