### ISSUE TITLE
Secret Key on Asp .net WebForms sample

### ISSUE THREAD

**Issue by lylia** [LtiLibrary/LtiLibrary#10]
Hi,

in the web Form part of Lti .net Sample, i notice that the ltiRequest contains ConsumerKey, url and ResourceLinkId  
 var ltiRequest = new LtiRequest(LtiConstants.BasicLaunchLtiMessageType)
            {
               ConsumerKey = "12345",
                ResourceLinkId = "launch",
                Url = new Uri(context.Request.Url, "Tool.aspx")
}

my question is, in wich part the Secret Key is added? 

Thanks.

**Comment by lylia** [comment]
i thinks that i've the answer,
here:  public static void WriteLtiRequest(this HttpResponse response, LtiRequest request, string consumerSecret);

**Comment by andyfmiller** [comment]
I'm glad you found your answer.
