### ISSUE TITLE
Any plans to support 1.2/1.3?

### ISSUE THREAD

**Issue by srijken** [LtiLibrary/LtiLibrary#100]
Handle this just as a question, I'll create new issues when the answer to this is positive :)
Are there any plans to support LTI 1.2 / 1.3? What needs to happen for this?

**Comment by andyfmiller** [comment]
The library does support 1.2, although that isn't saying much. There is not much difference between 1.1.1 and 1.2, https://www.imsglobal.org/specs/ltiv1p2.

I do plan on adding support for LTI 1.3 and all of LTI Advantage when it is finalized. That shouldn't be too hard either. A lot of Assignment and Grade Services and Names and Role Provisioning Services are already in the library.

**Comment by andyfmiller** [comment]
I just started a new branch for [LTI Advantage](https://github.com/andyfmiller/LtiLibrary/tree/advantage). At a minimum this will include support for:

- LTI v1.3
- Assignment and Grade Services v2.0
- Names and Role Provisioning Services v2.0
- Deep Linking v2.0

**Comment by hemachand1989** [comment]
Hi Andy, I am using your LTI Library for launch and outcomes and it is fantastic. Could you please let me know by when this library can be extended to support LTI Advantage. Also could you please guide me any deep linking articles or samples that can help me start working on it.

**Comment by andyfmiller** [comment]
@hemachand1989 I'm having a hard time understanding the new security framework for LTI Advantage. Have you found any code samples for LTI 1.3?

Deep Linking 2.0 did not change much from 1.0. I have 1.0 implementation in the [Consumer](https://github.com/andyfmiller/LtiSamples/blob/master/Consumer/Controllers/ContentItemToolController.cs) and [Provider](https://github.com/andyfmiller/LtiSamples/blob/master/Provider/Controllers/ToolController.cs#L201-L275) samples.

**Comment by andyfmiller** [comment]
First slice of an LtiAdvantageLibrary over [here](https://github.com/andyfmiller/LtiAdvantageLibrary).
