### ISSUE TITLE
Parsing URIs in optional fields causes unnecessary failures

### ISSUE THREAD

**Issue by hempels** [LtiLibrary/LtiLibrary#101]
It would be nice if we could _tell the parser_ to ignore invalid data in optional properties, particularly things like member:image where a value might be there that isn't a parseable URI. Totally fine if those simply get treated like they aren't present.

**Comment by andyfmiller** [comment]
How would this help you? Did you often receive invalid data from a third parties in production?

**Comment by hempels** [comment]
Actually it came up for us trying to use a test/sample service stood up by an LTI Consumer we're working on an integration with. In this case we were able to work around it by moving to a different version of their service, but the reality is the spec does not say those have to be valid URLs; we're fine with just ignoring them (possibly even in production) if a consumer sends data in those fields which can't be interpreted as a url.

In general, since we have no control over what a consumer sends, also having no control over how it's parsed (made more difficult since the parser wants to read the request stream directly meaning we can't modify it) puts us in a rather helpless position as users of both a service we can't control and a client we can't control.

**Comment by xferra** [comment]
I think you're talking about conditional property (de)serialization, it's not so trivial especially coz it introduces extra complexity and you should take control over all properties and show proper message in case of error (required is missing, parsing error, etc.).

Here you can find a simple [example](https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm) There are several other places where you can inject this logic, here is my [experiments](https://github.com/repometric/linterhub-cli/blob/master/src/core/Utils/ShouldSerializeConverter.cs#L115) in the same area (note that I implemented opposite logic, I skipped property serialization depending on some conditions).

So far so good, IMHO the easies way will be a create a custom build of this lib with the functionality you need OR [re-throw the exception here](https://github.com/andyfmiller/LtiLibrary/blob/88d6e676e6e08dc1e3c1a96e2fb9666eb1dc563d/src/LtiLibrary.NetCore/Extensions/JsonLdExtensions.cs#L71) passing the response body, so the caller will be able to handle its as needed.

Hope it helps 🤞

**Comment by jeroenhabets** [comment]
PR https://github.com/LtiLibrary/LtiLibrary/pull/104 was merged in 2018 so closing this now. Thanks @andyfmiller 🥇
