### ISSUE TITLE
LTI Integration with existing Asp.net application in VS2008 with 3.0 Framework

### ISSUE THREAD

**Issue by yogeshppatel** [LtiLibrary/LtiLibrary#102]
Hi Everyone, 

I would like to know that is it possible that our native  application (with framework .NET 3.0 and continue in VS2008) of Student Information System can be integrated with IMS GLobal LMS with LTI Integration (upgration is almost not possible).

As we understood ,with regards to IMS global LMS, out native application considered as Tool Provider (TP) right ?

Can someone guide step by step process,approach for LMS LTI integration with this kind of application. we don't have this app. has features like Rating app where students will need to rate but Students just need to use to get their educational info..

Also Single Sign on (OAuth) process (which is require for LTI ) will be possible for same environment(.NET 3.0)
Your help will be appreciated. 

Thanks
Yogesh

**Comment by andyfmiller** [comment]
Hello Yogesh,

If I understand correctly, your product is a Student Information System (SIS). Is it true that schools use your SIS to manage enrollments (for example, student A is enrolled in 3 classes that meet at school B)? And do schools also use your SIS to maintain the official "gradebook"?

**Comment by yogeshppatel** [comment]
Hi Andy , 
Thanks for your kind reply. 

1) Yes it is true that We have a small product (http://campusindia.co.in/CampusIndiaBrocure.pdf) same like SIS you mentioned which is mainly used for College Students Registration , Fees and some other modules .

2) Consider our product (Same like SIS) does NOT  maintain any gradebook (bcoz at University level it can not be considered and it is not kind of gradecard which is LMS result for any course. ) 

  But from LMS Platform , users (students and other staff) should be able to use our product using their common username/email id provided in LMS through institute. 

if you require i can provide more info. 

Many thanks
