### ISSUE TITLE
thrown when parsing roles from blackboard learn's membership service

### ISSUE THREAD

**Issue by Abziz** [LtiLibrary/LtiLibrary#109]
exception is thrown at [JsonLdContextRoleConverter.cs](https://github.com/andyfmiller/LtiLibrary/blob/master/src/LtiLibrary.NetCore/Lis/v1/JsonLdContextRoleConverter.cs#L34) when trying to parse roles from **blackboard learn**'s membership service.
```c#
if (Enum.TryParse(value.Substring(5), out ContextRole contextRole))
{
	return contextRole;
}
throw new JsonSerializationException($"Cannot convert {value} to {objectType.Name}.");
```

for example here parameter `value` would be equal to `urn:lti:role:ims/lis/Learner` and it wont parse to `ContextRole.Learner` so it would throw the exception in after the if block;

**Comment by adbindal** [comment]
The changes in #132 should take care of this issue.
