### ISSUE TITLE
Thread Safety in Outcomes1Client

### ISSUE THREAD

**Issue by tscbp** [LtiLibrary/LtiLibrary#115]
The product I work on (which functions as a Provider) is in the process of moving to .NetCore.  We were leveraging the .Net Framework edition of the library, and seeing a NetCore implementation, we were hoping we could continue to use it.  However, we've run into a couple of problems.

The primary one is that we lost access to a helper method for correctly generating the OAuth signatures - it seems this is only available through the LtiRequest object now.  This is not ideal, because we do not always want to 'send' or use the LtiRequest object as such.  In particular, when we are sending grade results via the Outcomes service protocol.

Seeing the Outcomes1Client, we thought to use that in place of our own code for serializing and sending the messages, but there we ran into what seems to me to be a code bug.  The `ReplaceResultAsync` method calls `SecuredClient.SignRequest`, which ends up on this line: https://github.com/andyfmiller/LtiLibrary/blob/master/src/LtiLibrary.NetCore/Clients/SecuredClient.cs#L90 - modifying the DefaultRequestHeaders object on the client.  As noted here: https://docs.microsoft.com/en-gb/dotnet/api/system.net.http.httpclient?view=netcore-3.1 HttpClient is meant to be created and reused within the application, so modifying a passed-in HttpClient in this way is very dangerous; moreover, the values that are being set in this header are specific to a single request (nonce, etc) and should not be reused, which is the general behavior of modifying `DefaultRequestHeaders`.

I am willing to take a shot at a PR that addresses this, but before I do, can you confirm that you are still accepting and reviewing PRs?  Or, per comments in other issues, is there a different library for 1.1 that I should be looking at?

**Comment by srijken** [comment]
I saw you did the PR :) I'm still busy setting up CI builds, so bear with me. Looks like a very welcome change, I've been wanting to do this myself :)
