### ISSUE TITLE
README

### ISSUE THREAD

**Issue by The-Futurist** [LtiLibrary/LtiLibrary#118]
Hi, 

We leveraged these libraries around three/four years ago to help us build LTI Tools and it's served us well. I'm now reviewing our LTI Tool framework and wanted to leverage the newer version of this as we plan to begin hosting our LTIs in the cloud and leverage Angular etc.

Something that has not changed though is the contents of the projects' README files, the simply contain a single line like this:

".NET library for IMS LTI 1.0, 1.1, 1.1.1 and 1.2; Outcomes 1.0; Outcomes 2.0 (Draft); and Content-Item Message 1.0."

It would be most helpful to elaborate some more in these README files to convey what kind of problem each one solves.

I take it (if I recall) that the AspNetCore library is intended for systems that want to host LTI Tools and the NetCore library is intended for the actual implementation of LTI Tools.

It would be nice to clarify this and say a little more about the intended use of each library, basic details about the overall structure, perhaps a sample LTI Tool and a sample LTI Tool host etc.

Thanks!

**Comment by jeroenhabets** [comment]
Hi @Korporal, I'll close this old ticket of yours now. In March 2020 @srijken updated dependency info of the README. If you'd  like more clarification please create a PR with your suggested README.md. Cheers, Jeroen
