### ISSUE TITLE
Could not compile from sources

### ISSUE THREAD

**Issue by xferra** [LtiLibrary/LtiLibrary#12]
It's not possible to compile library from sources (VS 2013, **.NET 4.5**).
For example this operator **.?** is not supported:
https://github.com/andyfmiller/LtiLibrary/blob/master/LtiLibrary.Core/Common/JsonLdObjectConverter.cs#L137

Could you update sources please so we will be able to dubug our app and execute unit tests?

**Comment by jeroenhabets** [comment]
Andy,

I suppose VS 2013 .NET 4.5 should still be supported by your library, correct? If so, will you remove these too recent C# language features and when? Or are his build settings not correct?

Thanks for your response,
Jeroen

**Comment by andyfmiller** [comment]
I reverted the VS 2015 C# features that VS 2013 C# does not understand. I will not be able to thoroughly test or push to NuGet for several weeks. If you find any bugs, please report them.

And remember, I gladly accept pull requests...don't be afraid to update the sources yourself and submit the changes you needed to make as a pull request.
