### ISSUE TITLE
Automate release publish to Nuget

### ISSUE THREAD

**Issue by srijken** [LtiLibrary/LtiLibrary#121]
- [x]  Publish to GitHub GPR
- [x]  Configure SemVer
- [ ]  Publish to feedz.io
- [ ]  Publish to NuGet.org

**Comment by srijken** [comment]
@andyfmiller Could you take these actions?

At both these locations, can you add "LtiLibrary" as an owner? It's an org I created at Nuget.org so multiple people can manage that as well.

https://www.nuget.org/packages/LtiLibrary.NetCore/3.1.1/manage/
https://www.nuget.org/packages/LtiLibrary.AspNetCore/3.1.1/manage/

Thanks a lot!

**Comment by amiller-ims** [comment]
Done. Sorry for the delay.

**Comment by srijken** [comment]
No worries, thanks!
