### ISSUE TITLE
Add package version for ASP.NET Core >=3.0.0

### ISSUE THREAD

**Issue by JanWichelmann** [LtiLibrary/LtiLibrary#124]
I am using this library in an ASP.NET Core 3.1 project, and get "ambiguous call" errors when using certain ASP.NET framework methods.

These errors are caused by the ASP.NET Core 2.0.0 dependency of LtiLibrary.AspNetCore. Temporarily removing the LtiLibrary.AspNetCore package fixed those problems.

Could you add another version that also supports ASP.NET Core >=3.0.0?

**Comment by srijken** [comment]
This problem was fixed, see #116  Can you check that you have version 3.2.0 installed?

**Comment by JanWichelmann** [comment]
Yes, just yesterday I was working on a follow-up .NET Standard 2.1 library that provides some utility functions for Moodle, and referenced LtiLibrary.NetCore and LtiLibrary.AspNetCore 3.2.0. Both packages are installed with version 3.2.0.

However, the Microsoft.AspNetCore dependency was pulled with version 2.0.0:
![packages](https://user-images.githubusercontent.com/5447131/77927338-68b4b680-72a7-11ea-97d0-1cf50f7a6e13.PNG)
I verified again, all packages are shown as up-to-date in VS.

I [have worked around this temporarily](https://github.com/Janworks/MoodleLti/commit/636e6e197707ea535e3a3d0042af6a9da1efb9ce) by copying the one source file I needed from the LtiLibrary.AspNetCore library, and then removing the dependency.

Edit: This even happens when I add the LtiLibrary.AspNetCore library to a new ASP.NET Core 3.1 project, so it is probably not related to my library targeting .NET Standard 2.1.
