### ISSUE TITLE
Release date of 1.6 (to NuGet) / LTI Outcomes issue

### ISSUE THREAD

**Issue by jeroenhabets** [LtiLibrary/LtiLibrary#13]
Hi Andy,

1) When do you plan to release version 1.6 of your library to NuGet? (see also [Issue #6 LTI Outcomes 2.0 - LISResult additional terms](https://github.com/andyfmiller/LtiLibrary/issues/6)) 

2) FYI I attended an IMS Global conference in Utrecht last week (great stuff!), and was invited to post my feedback on LTI to the IMS LTI forum. Which I did on Friday: [Limitations of LTI Outcomes 1.0/2.0 in a European context](http://www.imsglobal.org/community/forum/messageview.cfm?catid=44&threadid=1967)

Any feedback on the date and your thoughts on my LTI forum post are much appreciated!

Thanks in advance,
Jeroen Habets

**Comment by jeroenhabets** [comment]
Poke

**Comment by jeroenhabets** [comment]
Hi Andy, 
I'm getting worried this project has been abandoned. Could you please confirm the status of this project? (Of course, dead or alive is fully your prerogative). 
Regards, Jeroen

**Comment by eak65** [comment]
I hope it is not dead.

**Comment by andyfmiller** [comment]
I have not had the bandwidth to keep this project up to date for quite a while. Starting today I plan on spending time on the project. I will also let you know if that changes again so that you are not left wondering.

**Comment by srijken** [comment]
@andyfmiller that's great news. I think it's beneficial for the project when the workload is shared between a couple of people, so we can keep it moving also when you don't have the time. I wonder what's your take on this?
Maybe the best way to handle this is setting up a github organization for this project? Any ideas welcome

**Comment by andyfmiller** [comment]
@srijken I don't know anything about github organizations. Can you point me to an example?

In the near term, and without any changes, pull requests seem like a great way to go. I have received a couple in the past and it was very easy/quick to review and merge them into the project.

**Comment by jeroenhabets** [comment]
Hi Andy,
Great to hear you're back. Can we expect a NuGet release soon?
Regards, Jeroen

**Comment by andyfmiller** [comment]
Absolutely. This week unless you or anyone else finds a bug in the changes
I checked in over the last few days.

Andy

**Comment by andyfmiller** [comment]
It is taking me longer than I thought to get 1.6 ready. My goal for 1.6 is to add support for the Outcomes-2 draft from December 2014.

There has been a lot of discussion on the IMS member forums since then about how to implement certain features. I've got the LineItems service working, but I have not been able to pass the draft certification tests yet. I'm also adding the Results service. Once they both pass the draft cert tests, I'll post a new NuGet package.

I put out 1.6.1 after Outcomes-2 is final and I incorporate any changes between draft and final.

**Comment by andyfmiller** [comment]
I think I finished Outcomes-2. It works well with http://lti.tools/test/tp.php. I will put out a new NuGet package after I pass the Outcomes-2 certification tests.

**Comment by andyfmiller** [comment]
After a few more tweeks, passed all the Outcomes-2 (draft) certification tests: http://screencast.com/t/kpTbcdbk

Next up is to build the NuGet package.

**Comment by andyfmiller** [comment]
1.6 is out
- https://www.nuget.org/packages/LtiLibrary.Core/
- https://www.nuget.org/packages/LtiLibrary.AspNet/
