### ISSUE TITLE
ParseLtiRequestAsync Doesn't Accept application/json payload

### ISSUE THREAD

**Issue by khairu-aqsara** [LtiLibrary/LtiLibrary#141]
Hi, I would like to know how can we accept the  application/json payload format ? right now it's seems just accept the `request.HasFormContentType` for LTi Request, is it possible to add application/json payload format ? some LMS seems send the LTI request using these json payload.

I doing some additional step before validate and process the LTI Request like

```
if(Request.ContentType.Equals("application/json")){
   // Process the JSON payload as ltiRequest 
}else{
    var ltiRequest = await Request.ParseLtiRequestAsync();
}
```

but i think that could be a better way to doing it.

**Comment by jeroenhabets** [comment]
Hi @khairu-aqsara ,

Not a code contributor but I can try to chime in here:

This repository is for LTI 1.1. As LTI 1.3 moved to JSON payloads, a.o. for a more modern security framework, I believe you're actually looking for LTI 1.3 support.

I kindly refer you to the sibling [LtiAdvantage](https://github.com/LtiLibrary/LtiAdvantage) for that.

Kind regards, Jeroen

http://www.imsglobal.org/lti-advantage-overview

**Comment by khairu-aqsara** [comment]
yeah I think you right,   I'll take a look on the LTI 1.3 then, thank you.
