### ISSUE TITLE
LtiRequest - No constructor to create from a POST FORM 

### ISSUE THREAD

**Issue by The-Futurist** [LtiLibrary/LtiLibrary#147]
I a tool request service we're designing we get a POST from the tool consumer and need to create an LtiRequest from that. In a fork we have added a new constructor that does this:

```cs
        public LtiRequest(string HttpMethod, string Url, IEnumerable<KeyValuePair<string, string>> Fields)
        {
            this.HttpMethod = HttpMethod;
            this.Url = new Uri(Url);

            foreach (var field in Fields.Where(kv => kv.Key != "oauth_signature"))
            {
                InternalParameters[field.Key] = field.Value == null ? "" : field.Value;
            }
        }
```
I wondered, is there a reason why such a constructor is not already present? Is there a preferred way to create this object from a raw POST request?

**Comment by jeroenhabets** [comment]
Hi @Korporal,

My 2ct: doesn't `ParseLtiRequestAsync(this HttpRequest request)` achieve what you're after?
https://github.com/LtiLibrary/LtiLibrary/blob/cc1d1777b51b4c36a85b0a625051ec2a5e143792/src/LtiLibrary.AspNetCore/Extensions/HttpRequestExtensions.cs#L106

Cheers, Jeroen

**Comment by The-Futurist** [comment]
> Hi @Korporal,
> 
> My 2ct: doesn't `ParseLtiRequestAsync(this HttpRequest request)` achieve what you're after?
> 
> https://github.com/LtiLibrary/LtiLibrary/blob/cc1d1777b51b4c36a85b0a625051ec2a5e143792/src/LtiLibrary.AspNetCore/Extensions/HttpRequestExtensions.cs#L106
> 
> Cheers, Jeroen

I wasn't aware of that Joe, thanks! I crafted a solution last year, so the problem is more or less solved now. I created a bare bones .Net 7 library from a subset of the LTI source and this is working now. I will definitely look into this other method though, perhaps leverage it rather than reinventing the wheel!

**Comment by jeroenhabets** [comment]
Great to hear @Korporal ! Though let's hope also the smaller players complete the move to LTI 1.3 aka LTI Advantage soon (see sibling [LtiAdvantage](https://github.com/LtiLibrary/LtiAdvantage) library for .Net "Core").
