### ISSUE TITLE
How to create LtiDeepLinkingResponse in LTI 1.3 using .NET Core

### ISSUE THREAD

**Issue by kartik-scholarlab** [LtiLibrary/LtiLibrary#149]
We are trying to implement LTI 1.3 Deep Link, but we cannot get the LtiDeepLinkingData class reference from anywhere - which library do we need to install? Any ideas on how to proceed with LTI 1.3 Deep Linking implementation from .NET Core? Any help is appreciated

**Comment by jeroenhabets** [comment]
Hi @kartik-scholarlab I think you're looking in the incorrect repo. This "LtiLibrary" is for the old/obsolete LTI 1.1.

Please have a look at it's sibling [LtiAdvantage](https://github.com/LtiLibrary/LtiAdvantage) repo for the LTI 1.3 library for .Net "Core". And related to your question its `src/LtiAdvantage/DeepLinking` folder.

Cheers, Jeroen
