### ISSUE TITLE
Outcomes 2.0 LisResult issues (ResultAgent and ResultStatus)

### ISSUE THREAD

**Issue by jeroenhabets** [LtiLibrary/LtiLibrary#15]
Hi Andy,

As always, first a thank you for your great work!

My team is implementing the Outcomes 2.0 using your Library and running into some issues (I've logged a single ticket as they affect the same class):

If we compare the Draft specification (especially http://www.imsglobal.org/lti/model/mediatype/application/vnd/ims/lis/v2p1/result%2Bjson/index.html#LISResult)
to your implementation:
https://github.com/andyfmiller/LtiLibrary/blob/master/LtiLibrary.Core/Outcomes/v2/LisResult.cs

we encounter a couple of issues.

1) The spec says resultAgent is a LISPerson hence a compound "userid" with optional "id".
Your LisResult.cs dictates a URI.
==> A value of `{ "userid": "*userid*" }` should be provided/accepted (not an URI). (Of course the optional `"id"` should also be supported)

2) The spec says resultStatus is an enumeration that needs to be referenced by their simple names (Completed, Final, Initialized, Started).
Your implementation (un)marshalls from/to the enumeration index (e.g. `0` instead of `"Completed"`)
===> The simple names should be provided/accepted (not the enumeration index)

I eagerly await your feedback.

Regards,
Jeroen H
P.S. My team could provide a pull request if you agree with my interpretation of the spec.

**Comment by andyfmiller** [comment]
I'll take a look asap. I love pull requests!

**Comment by andyfmiller** [comment]
@jeroenhabets - I'm sorry I took so long to look at this. I imagine you have already fixed this locally.

I just checked in some changes to fix both issues and tested them with SimpleLti over in LtiSamples. I have not tried any certification tests yet.
