### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by xferra** [LtiLibrary/LtiLibrary#16]
Hello Andy,

Any plans to support .NET Core or ASP.NET Core?

WBR,
Andrey

**Comment by andyfmiller** [comment]
Hello Andrey,

Some people that use LtiLibrary have company policies that prevent them from using release candidates. So I should probably wait some time after RTM.

It is definitely in line with the way I broke up LtiLibrary into Core and ASPNET, so it should not be a technical challenge.

Have you or your company started using .NET Core and/or ASP.NET Core?

Andy

**Comment by jeroenhabets** [comment]
Hi Andy,
With vNext nearing release my company is actually contemplating using it for a development we are about  to start.

https://github.com/aspnet/Home/wiki/Roadmap

Regards,
Jeroen

**Comment by andyfmiller** [comment]
Hello Jeroen,

I just updated VS 2015 and now have RC2. Do you have any advice on things I should watch out for?

Andy

**Comment by jeroenhabets** [comment]
Hi Andy,

I'll ask my team but for us and on behalf of our partners, I'd say main thing to be careful for is to keep the library compatible with previous C#/.Net features.
We have moved to Roslyn and will start using vNext for new developments. But even we will have to keep on maintaining MVC 4.5 code.

Regards,
Jeroen

**Comment by xferra** [comment]
Hello Andy,

I've created a [pool request](25) as a first step towards migration to .NET Core (migrate from WebRequest to HttpClient).

Here you can find other portability issues:
![portabilityreport1](https://cloud.githubusercontent.com/assets/674129/15965469/b7481fa8-2f26-11e6-99fb-f830efcbd9ac.jpg)

Andrey

**Comment by xferra** [comment]
Finally, I've [added support](25) for multiple targets (NET 4.5, NET 4.6, NET Standard 1.5, NET Core 1.0) for LtiLibrary.Core and updated source code (You can use separated LtiLibrary.NetCore solution for that).

**Comment by andyfmiller** [comment]
@xferra Can I close this issue, or do you think there is more to do?

**Comment by xferra** [comment]
@andyfmiller this project is still not ready for ASP.NET Core, and MS guys introduced some [breaking changes](https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/) recently. We can close this issue as far as LTI.Library.Core is more or less ready and split upcoming changes into a smaller issues, what do you think?

**Comment by andyfmiller** [comment]
Let's do that.

**Comment by xferra** [comment]
Ok, i will close this one.
