### ISSUE TITLE
HTTP Error 403.14 - Forbidden

### ISSUE THREAD

**Issue by ramkumarbcs** [LtiLibrary/LtiLibrary#17]
Hi,
First of all, thanks for your excellent work.

I download the source code. and run VS2013. The below error comes.

![image](https://cloud.githubusercontent.com/assets/17613156/13566625/675526ac-e47c-11e5-807b-51cde9947907.png)

Kindly help us.

**Comment by andyfmiller** [comment]
The projects in LtiLibrary cannot be run. They are libraries meant to be referenced by your web site code. 

There are some sample projects over in https://github.com/andyfmiller/LtiSamples that can be run.
