### ISSUE TITLE
LtiLibrary.Core dll with strong name

### ISSUE THREAD

**Issue by aaronmfy** [LtiLibrary/LtiLibrary#20]
I am trying to apply LtiLibrary.Core dll to my project. Since my project is signed, and it throws error said "Assembly generation failed -- Referenced assembly 'LtiLibrary.Core' does not have a strong name". In this case, how should I use your dll, could you provide me a strong name version?

**Comment by andyfmiller** [comment]
@aaronmfy I have signed both assemblies, attached them to the 1.6.1 release here in GitHub and published them on NuGet. I hope that helps.
