### ISSUE TITLE
Support Additional Signing methods

### ISSUE THREAD

**Issue by dunlapm** [LtiLibrary/LtiLibrary#22]
Are there any plans to support additional OAUTH signing methods (RSA-SHA1, or even the SHA256 equivalents)? 

It would be wonderful to be able to use other signing methods as required. Everything looks to be hard-coded to HMAC-SHA1.

**Comment by jeroenhabets** [comment]
@dunlapm could you point to where in the LTI specification it says support for other signing methods is required?

AFAIK: 
- LTI  1.0 required HMAC-SHA1 to be the _one and only_ signing method (see https://www.imsglobal.org/specs/ltiv1p0/implementation-guide#toc-14)
- LTI 1.1+ and 2.0 requires only HMAC-SHA1 to  be supported. But allows more in the lti_oauth_hash_message_security Profile. While the other lti_oauth_body_hash_ws_security Web Services Security Profile still requires the signing method to be _only_ HMAC-SHA1.

See e.g. the LTI 2.0 security specification:
lti_oauth_hash_message_security Profile (https://www.imsglobal.org/specs/ltiv2p0/security#toc-8)
"Tool providers must support at a _minimum_ the **HMAC-SHA1** signing method with OAuth data passed as POST data."

lti_oauth_body_hash_ws_security Web Services Security Profile (https://www.imsglobal.org/specs/ltiv2p0/security#toc-9)
"oauth_signature_method’ : the value of this parameter should be ‘HMAC-SHA1’"

My interpretation would be that supporting other signing methods is never required and only allowed for the lti_oauth_hash_message_security Profile. (Am I correct @spvickers?)

**Comment by spvickers** [comment]
At present LTI only uses the HMAC-SHA-1 for all its signatures.  LTI 2.1 is expected to introduce the option of using HMAC-SHA256 but, as many of the OAuth 1 libraries do not implement this, we are also proposing a new security model using JWTs (and SHA-256).  HTH.

**Comment by dunlapm** [comment]
LTI 1.1.1 specifies that HMAC-SHA1 to be the *minimum *supported signing
method. Which means to me that others may be supported if both the provider
and consumer agree on a method.

For 2.0, it says "In order to support as many OAuth client libraries and
approaches as possible, tool providers are encouraged to support as many
OAuth signature types as possible as well as support receiving OAuth data
in headers, in URLas query parameters, or in POST parameters."

-Michael Dunlap

**Comment by jeroenhabets** [comment]
@dunlapm so in summary it would be "wonderful" but it is not required by the spec.

**Comment by dunlapm** [comment]
@jeroenhabets Yes, though as I see it, it's currently impossible for a user of this library to support any methods other than SHA1.

**Comment by andyfmiller** [comment]
@dunlapm - I agree, the library does not support any other methods than SHA1. As spvickers noted, IMS recently floated the idea of using JWTs as an alternative to OAuth signatures. AFAIK that proposal has not made it into any spec yet.

Do any other libraries support alternatives to SHA1? If yes, then it makes sense to add support to LtiLibrary. If not, then I think there are other, more pressing, issues.

**Comment by srijken** [comment]
@jeroenhabets Where in the documentation did you find this:

> LTI 1.1+ and 2.0 requires only HMAC-SHA1 to be supported. But allows more in the lti_oauth_hash_message_security Profile. While the other lti_oauth_body_hash_ws_security Web Services Security Profile still requires the signing method to be only HMAC-SHA1.

We're seeing increased demand for supporting HMAC-SHA256

**Comment by jeroenhabets** [comment]
@srijken in my post I summarized the spec and provided references to the appropiate sections in the appropiate specifications. Please read that carefully, bearing in mind that if and only if I quote (specifications), I use quotes.
