### ISSUE TITLE
Potential Security Hole?

### ISSUE THREAD

**Issue by ptyork** [LtiLibrary/LtiLibrary#24]
First, this library is fantastic. Thanks! I'm currently integrating this into a TP application written in MVC and using the OWIN libraries (ASIDE: would be nice if the OWIN components were available via NuGet, but building from source has been a good learning exercise).

When you authenticate using LTI, the code eventually calls SecurityProvider.OnAuthenticated. This method does one of three things.

1) If there's already a matching external login, it logs in...cool.
2) If there's no matching external login and no user matching the username in the LTI request, it creates a new user and logs in...also cool.
3) If there's no matching external login but a user with a matching username, it adds the external login to the existing user and logs in...hmmmm.

In the third case, it would seem possible that someone could spoof the system by creating an account in a tool consumer using another user's email address and gain access to their TP account this way.

Now I suppose that you could assume some "trust" in the tool consumers (i.e., that they wouldn't allow users to create accounts using unconfirmed email addresses), but that might not be possible for a publicly available TP, especially if you provide a consumer registration URL.

Just curious if there is any best practice here to prevent this? Short of forcing a unique username per consumer, I suppose. Is there a way to integrate some kind of email validation into the library, or maybe expose a hook to allow us to do it ourselves? I.e., perhaps have a callback that fires when this issue arises...an else condition after SecurityHandler:49?

Note, though, that if the user happens already to be logged in to the TP, then if the usernames DO match you'd definitely want to allow the linking of the TC account.

Anyway, long winded question. But I'd be happy to submit a pull request with this implemented if you feel as though it's an issue worth "fixing."

**Comment by andyfmiller** [comment]
@ptyork - Thank you! The OWN stuff is on NuGet, but as [Alpha](https://www.nuget.org/packages/LtiLibrary.Owin.Security.Lti/), partly because it made me feel uneasy security wise.

There is supposed to be a level of trust between the TC and the TP via the secret that is only known by those two parties. But I too feel like there should be something more if the TP and TC are sharing personal information.

What I have seen in practice is TPs requiring the account to be created outside of the LTI flow.

**Comment by andyfmiller** [comment]
@ptyork - I'm going to close this issue, but please feel free to continue the discussion.
