### ISSUE TITLE
A Quick Start Required

### ISSUE THREAD

**Issue by aliarshadpro** [LtiLibrary/LtiLibrary#29]
Hi @andyfmiller,
Hope you will be fine. I am a beginner in LTI. I am reading your old quick start guide but it isn't helpful that much. It will be very nice if you can give me a quick start for working with LTILibrary in .net. Thanks in advance.

@xferra please if you can help me too.

Regards

**Comment by xferra** [comment]
Hello @emcyborg , are you developing LTI consumer or provider?

**Comment by emcyborg** [comment]
Consumer ... I am trying to integrate BigBlueButton using LTI n BBB is using 1.x version of LTI
________________________________

**Comment by aliarshadpro** [comment]
Hello @xferra,
Consumer ... I am trying to integrate BigBlueButton using LTI n BBB is using 1.x version of LTI.

Anxiously waiting for your response.

**Comment by xferra** [comment]
@emcyborg You may check some [examples](https://github.com/andyfmiller/LtiSamples) developed by @andyfmiller. I also suggest moving this issue to a proper repository (LtiSamples). If you have any questions please let me know.

**Comment by aliarshadpro** [comment]
@xferra I already checked them but they are not working in asp.net core

**Comment by xferra** [comment]
@emcyborg LtiLibrary was initially developed for .NET 4.5, I'm in progress of adding support for .NET Core (Pull request #25), but it's not finished yet.
You can also follow this issue #16, I will let you know when the library will be ready for .NET Core.

**Comment by aliarshadpro** [comment]
@xferra Roger that ... I am waiting for your response anxiously
