### ISSUE TITLE
HttpResponse is not disposed

### ISSUE THREAD

**Issue by valiukevich** [LtiLibrary/LtiLibrary#32]
The latest version available on NuGet has this issue.

Example:LtiLibrary\LtiLibrary.Core\Outcomes\v2\OutcomesClient.cs
Method - PostOutcome

HttpWebResponse response = null;
                    try
                    {
                        **response** = (HttpWebResponse)request.GetResponse(); 
//response is not disposed. it leads to timeouts when all connections are used. //http://stackoverflow.com/questions/1994417/c-sharp-http-web-request-keeps-timing-out
                        outcomeResponse.StatusCode = response.StatusCode;
                        if (response.StatusCode == HttpStatusCode.Created)
                        {
                            outcomeResponse.Outcome = response.DeserializeObject<T>();
                        }
                    }
                    catch (WebException ex)
                    {
                        response = (HttpWebResponse)ex.Response;
                        outcomeResponse.StatusCode = response.StatusCode;
                    }
                    catch (Exception)
                    {
                        outcomeResponse.StatusCode = HttpStatusCode.InternalServerError;
                    }
                    finally
                    {
# if DEBUG

```
                    outcomeResponse.HttpRequest = request.ToFormattedRequestString();
                    if (response != null)
                    {
                        outcomeResponse.HttpResponse = response.ToFormattedResponseString(
                            outcomeResponse.Outcome == null
                            ? null
                            : outcomeResponse.Outcome.ToJsonString());
                    }
```
# endif

```
                }
```

**Comment by jeroenhabets** [comment]
Hi @valiukevich, 
The latest version on [NuGet](https://www.nuget.org/packages/LtiLibrary.Core/) is currently 1.6.1. Could you provide a pull request for the issue you reported based on [1.6.1](https://github.com/andyfmiller/LtiLibrary/tree/1.6.1) so it could lead to a 1.6.2 if @andyfmiller agrees?
TIA, Jeroen

**Comment by valiukevich** [comment]
Hi @jeroenhabets and @andyfmiller 

The pull request #33  has been submitted.

With this fix all integration tests I have (around 100) on outcomes 1 and 2 are passed.

**Comment by andyfmiller** [comment]
@valiukevich - Rather than merge the pull request into master (which is way ahead of 1.6.1), I rebuilt the packages on NuGet directly from your pull request. Version 1.6.2 of LtiLibrary.Core and LtiLibrary.AspNet are now on NuGet.

**Comment by andyfmiller** [comment]
Closing this issue now that this has also been merged into the v1.7.0 branch.

**Comment by xferra** [comment]
@andyfmiller My two cents that next version should be v2.0, as far as some major changes were introduced in the library.

**Comment by andyfmiller** [comment]
That's fine with me.

I've started a new issue #36 to collect the changes (I'll turn them into release notes in NuGet).
