### ISSUE TITLE
Invalid JsonProperty

### ISSUE THREAD

**Issue by jallanson** [LtiLibrary/LtiLibrary#34]
The JsonProperty in LtiLibrary.Core.Outcomes.v2.Activity for ActivityId is set as "activity_id", however the spec for LTI Outcomes 2.0 lists this property as "activityId".

**Comment by andyfmiller** [comment]
Right you are (https://www.imsglobal.org/lti/model/mediatype/application/vnd/ims/lis/v2/lineitem%2Bjson/index.html#Activity). Context too (https://www.imsglobal.org/lti/model/mediatype/application/vnd/ims/lis/v2/lineitem%2Bjson/index.html#Context).

I'll fix this after pull request #35 is merged.

**Comment by xferra** [comment]
@andyfmiller PR #35 was merged.

@jallanson You can expect the fix for `activityId` soon.

**Comment by jeroenhabets** [comment]
I was about to log an issue about the fact that @context is mandatory in Outcomes 2.0 but the library does not automatically insert the default value if none is set.

Is that part of the proposed fix?

TIA

**Comment by andyfmiller** [comment]
What would be a good default value? A default value might hide a logic problem in the application using this library. I think it might be better to keep the current default (null).

**Comment by xferra** [comment]
@andyfmiller I think that it will be a good idea to throw an exception (when sending a request) if mandatory/required value was not provided, what do you think?

**Comment by andyfmiller** [comment]
That's a great idea. It would match the LtiLibrary behavior for launch requests. Probably outside the scope of this issue though.

**Comment by andyfmiller** [comment]
Created a new issue #38 to throw an exception (when sending a request) if mandatory/required value was not provided.
