### ISSUE TITLE
Invalid OAuth signature or timestamp

### ISSUE THREAD

**Issue by nm4568** [LtiLibrary/LtiLibrary#4]
Hi Andy,

I'm not sure what changed in how the oauth_signature is generated between 1.4.5 (1.4.5418.33006) and your most recent build (pulled from GitHub yesterday) but it is somehow generating an invalid OAuth Signature or Timestamp error within the LTI 1 Certification Test Suite. I verified that the 1.4.5 library has no issues with the LTI 1 Certification Test Suite. Also, I have thought of comparing the source files but I am unable to find the source for the 1.4.5 library and I only have a Nuget package.

I am calling the method, 'GetLtiRequestViewModel' within the LtiRequest class.

Please let me know if you need any more information or if I can help in any way.

Thanks,
Nathan Moebus

**Comment by rikkreeftenberg** [comment]
Hi Nathan,

This might have something to do with the fix of an issue calculating the signature in combination with querystrings. 
Have a look at https://github.com/andyfmiller/LtiLibrary.Owin/issues/1

Regards,

Rik

**Comment by nm4568** [comment]
Hey Rik,

Thanks for replying.  My launch URL does in fact use the query string.  I have checked the OAuthRequest.GenerateSignature function and I see that the query string is being added to the parameters collection before the signature is generated.

![generatesignature](https://cloud.githubusercontent.com/assets/3853981/6941035/f89fbaa4-d849-11e4-92ef-c12a20b44dbd.PNG)

I think what would be really helpful is if i can get a copy of the source from the 1.4.5 release and diff the sources.

Thanks,
Nathan

**Comment by nm4568** [comment]
Hi Andy/Rik,

I did manage to find an older version of the LTI source and have figured out what the issue is.  The issue manifests when the launch URL has encoded querystring parameters (i.e. http://www.imsglobal.org/developers/alliance/LTI/cert/tc_tool.php?x=With%20Space&y=yes).  Within the GenerateSignature function of the OAuthRequest class, the following line of code does not decode the querystring parameters before being added to the parameters collections and generating the signature which is causing the error.

var querystring = new UrlEncodingParser(Url.Query);

Within the older code base, the querystring parameters are decoded before being added to the parameters collection within the ParseQueryString function which works just fine.

var querystring = HttpUtility.ParseQueryString(Url.Query);

Thanks,
Nathan

**Comment by andyfmiller** [comment]
Thank you Rik and Nathan,

This is now fixed: https://github.com/andyfmiller/LtiLibrary/commit/08c743bc5b4ee561b7096b3cb77cfe8cb16e1169

Andy
