### ISSUE TITLE
.NET 4.0 Support

### ISSUE THREAD

**Issue by dlenhardt** [LtiLibrary/LtiLibrary#5]
Hi Andy,

I wanted to see if there was a version of the LTI library that supported .NET 4.0.

Thanks!

**Comment by jeroenhabets** [comment]
We ran into the same question a year ago and ended up upgrading to .NET 4.5 (I would not advice to use a very old version of this library that might support 4.0 as it has seen quite a few fixes and improvements over the last year)

**Comment by andyfmiller** [comment]
I have not tried to build a version that supports .NET 4.0, but I will gladly link to one if you find/build one.
