### ISSUE TITLE
NetCore LtiRequest.CheckForRequiredLtiParameters lis_outcome_service_url being validated in error

### ISSUE THREAD

**Issue by CreepyGnome** [LtiLibrary/LtiLibrary#56]
I am new to LTI stuff, so I apologize in advance if I misunderstand something.

When I use your ConsumerCertification project in your LtiSamples solution, and I use the default CustomParameters when I use the Instructor Link 2 it throws an exception from the below method stating that `lis_result_sourcedid` is required. Your code is setup as such that if `lis_outcome_service_url` is not null or empty, then `lis_result_sourcedid` is required. 

In the 1.1 implementation guide, [section 6](https://www.imsglobal.org/specs/ltiv1p1/implementation-guide#toc-6), it talks about these two fields. I don't see anything about `lis_result_sourcedid` being required if the `lis_outcome_service_url` is provided. As a matter of fact, it seems to say that if `lis_outcome_service_url` is required if the TC accepts outcomes, and that regardless of whether or not the `lis_result_sourcedid` is provided. I do see a case for the reverse where if a `lis_result_sourcedid` is provided then the `lis_outcome_service_url` is required

Therefore, if I understand, correctly it seems the below check should not be occurring where it requires `lis_result_sourcedid` if there is a `lis_outcome_service_url`, and it probably should be reversed.

The method in question:
```csharp
    LtiLibrary.NetCore.Lti.v1.LtiRequest.CheckForRequiredLtiParameters
```
The code in question
```csharp
    // If the request is configured to support Outcomes 1.0, make sure lis_result_sourcedid is specified
    if (!string.IsNullOrWhiteSpace(LisOutcomeServiceUrl))
    {
        RequireAllOf(RequiredOutcomes1Parameters);
    }
```

**Comment by CreepyGnome** [comment]
Update:
Throws the same exception as above with Link1, Link 3, Link 7, and Link 8. 

Only seems to work with Link 4, 5, 6.

**Comment by andyfmiller** [comment]
Removed check for lis_result_sourcedid. Thank you for pointing this out.
