### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by wachulski** [LtiLibrary/LtiLibrary#59]
Are you going to support .NET Standard:
* in the nearest future
* at all?

**Comment by xferra** [comment]
@wachulski Could you please describe what is the issue with using .NET Standard 2.0 right now?

**Comment by wachulski** [comment]
I've got a legacy 4.5.2 project.

**Comment by xferra** [comment]
As far as I understand it uses 'classic' .NET, so you may use [LtiLibrary1.6](https://www.nuget.org/packages/LtiLibrary.Core) and corresponding [repository](https://github.com/andyfmiller/LtiLibrary1.6) for questions and issues.

**Comment by wachulski** [comment]
Yeah, I know. I've been considering that one. Since you offer libs, I wanted to know if and when you would make it .NET standard to reach more platforms than just net core. I don't want to argue here (*just net core* is still wide). I asked for pure information, but thx for trying to help me fit your offer.

Anyway - have you considered .NET Standard? Any plans to do so?

**Comment by xferra** [comment]
Seems like you're the first user who requested support for .NET Standard.
As you may see I made some efforts in the scope of Isssue #16 and PR #25, but in the end @andyfmiller decided to split projects and codebase (Core & Classic); so I suggest to address this question to him.
Personally - I do not have any concrete plans to implement it and I could help you if needed.

**Comment by wachulski** [comment]
Ok. Let's see what @andyfmiller thinks.

**Comment by brainiac10** [comment]
Converting to [.NET Standard 1.6](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) would be a good way to support older versions of .NET Core at the same time.  Right now, the LtiLibrary assemblies are built against .NET Core 2.0, and I can't use them with my .NET Core 1.0 apps.

**Comment by andyfmiller** [comment]
Have you tried changing the target to netstandard1.6 and compiling the current versions of LtiLibrary.NetCore and LtiLibrary.AspNetCore? If that works, then it would be a pretty simple matter to include multiple frameworks in the NuGet packages.

**Comment by andyfmiller** [comment]
Pull request #65 targets both netstandard1.6 and netstandard2.0. Anyone care to take a look?

**Comment by xferra** [comment]
Merged, doyou plan to update examples and ASP part?

**Comment by andyfmiller** [comment]
Thank you! I aspire to update LTI Samples, but it is hard to make the time. Which ones do you think are most useful?

What does "ASP part" refer to?

**Comment by xferra** [comment]
@andyfmiller I believe the consumer is the more widely used scenario. 

Offtopic: How about hosting the examples somewhere on the free plan in Azure/any other place? (so, developers may easily play with it)

**Comment by andyfmiller** [comment]
[Consumer](http://consumer.azurewebsites.net/) and [Provider](http://provider.azurewebsites.net/) have been on Azure for quite a while. And I recently added a [Google Classroom/LTI](http://gc2lti-outcomes.azurewebsites.net/) sample.

**Comment by andyfmiller** [comment]
I created https://github.com/andyfmiller/LtiSamples/issues/10 to track updating the consumer sample.

Closing this one.

**Comment by andyfmiller** [comment]
@xferra created a new [consumer-rp](https://github.com/andyfmiller/consumer-rp) repo hosted on [Azure](http://consumer-rp.azurewebsites.net/).
