### ISSUE TITLE
LTI Outcomes 2.0 - LISResult additional terms

### ISSUE THREAD

**Issue by jeroenhabets** [LtiLibrary/LtiLibrary#6]
Hi Andy,
I'm delighted to see that IMS Global has enriched the outcome of LTI. According to my understanding of the spec [[1]](http://www.imsglobal.org/lti/services/ltiOMv2p0pd/mediatype/application/vnd/ims/lis/v2p1/result+json/index.html#The_LISResult_Media_Type), specifically of  [2. The LISResult Media Type](http://www.imsglobal.org/lti/services/ltiOMv2p0pd/mediatype/application/vnd/ims/lis/v2p1/result+json/index.html#The_LISResult_Media_Type) , item 6 _The set of contexts imported by the root object MAY include additional terms that do not appear in the standard context [LIS-v2p1-Result]_
means that the LISResult JSON type MAY include additional non-standard terms. 

As far as I can tell your library does not provide a way to set nor retrieve these additional terms. The ability to support additional terms is key to success in the our (Dutch) market so if your library could support it that would be great.

What are your thoughts on this?
Regards, Jeroen
[1] http://www.imsglobal.org/lti/services/ltiOMv2p0pd/mediatype/application/vnd/ims/lis/v2p1/result+json/index.html#The_LISResult_Media_Type

**Comment by jeroenhabets** [comment]
up

**Comment by andyfmiller** [comment]
Hello Jeroen,

You must be right about the meaning of item 6...the ability to define the terms in the JSON is fundamental to [JSON-LD](http://www.w3.org/TR/json-ld/#the-context).

I am not happy with the JSON-LD support in LtiLibrary. For ToolConsumerProfile I added @Context, @id, and @Type properties to the class and basically hardcoded the context. That worked at the time. But outcomes added a twist...results can be sent alone (with their own context) or in a collection (the result context should be merged into the collection context). I started down the path of writing a serializer that would inspect the payload and construct a valid context, but did not get very far.

I spoke to someone at the recent IMS meeting that serializes the payload (without any context) then wraps that with a context. I'm sure that works, but it does mean the coder constructing the response has to know a lot about JSON-LD.

Just last week I was reading some Caliper code (not public yet) that handles context in a 3rd way. This weekend I hope to take another look at that to see if that is the approach I want to take. If nothing else, I'll make sure you can add your own terms to the context.

**Comment by jeroenhabets** [comment]
If we can add our own terms and of course retrieve them when receiving them that would be excellent news!

**Comment by jeroenhabets** [comment]
From the contents of recent commits, I gather you have resolved this issue in "master" and are preparing a **1.6** release. **Great!** 

Any idea, when you are planning to do the actual release to NuGet?

**Comment by andyfmiller** [comment]
There have been some changes to the Outcomes 2.0 draft since I added support. I need to go through the latest version and make corrections. But I have not been in a hurry since the spec is still in draft mode (and still changing).

**Comment by jeroenhabets** [comment]
We are starting a couple of projects that practically speaking depend on Outcomes 2.0. As in the past LTI Library releases have been made to add support voor Draft specifications, would it be possible to release 1.6 to NuGet somewhere in the next four weeks?

AFAICT The Outcomes 2.0 draft I found has not changed since December... If the recent changes you mentioned are somewhere else, could you post a link to them, please?

**Comment by andyfmiller** [comment]
If you are a contributing member, you will find a discussion in the member forums.

**Comment by jeroenhabets** [comment]
Thanks for your response but actually, my main question has been left unanswered: are you planning to/will you be able to do a NuGet release some time soon?
