### ISSUE TITLE
Outcomes broken

### ISSUE THREAD

**Issue by brainiac10** [LtiLibrary/LtiLibrary#60]
**Short version:**  
Model binding fails when posting to controllers inheriting from OutcomesControllerBase, with the end result being that no outcomes can be processed.

**Detailed version:**
For an Outcomes controller that inherits from OutcomesControllerBase, when it receives a [HttpPost request](https://github.com/andyfmiller/LtiLibrary/blob/master/src/LtiLibrary.AspNetCore/Outcomes/v1/OutcomesControllerBase.cs#L43), the imsx_POXEnvelopeType input parameter is always null, and the outcome request is lost.

This is because OutcomesControllerBase has the AddBodyHashHeader attribute on it.  When the AddBodyHashHeaderAttribute class calculates the hash, it [reads](https://github.com/andyfmiller/LtiLibrary/blob/master/src/LtiLibrary.AspNetCore/Common/AddBodyHashHeaderAttribute.cs#L31) the Request.Body stream, which can be of type FrameRequestStream.  That stream can't be reset to the beginning (CanSeek == false), so any code trying to read the body stream later on will fail.

[Here](https://github.com/andyfmiller/LtiLibrary/blob/master/src/LtiLibrary.AspNetCore/Outcomes/v1/ImsxXmlMediaTypeModelBinder.cs#L34) is where the problem happens.  The Request.Body stream is already at the end, so there's no xml to deserialize, and you get an exception.

**Comment by brainiac10** [comment]
Here's a [related issue](https://github.com/aspnet/KestrelHttpServer/issues/1548), to help explain the problem.

**Comment by andyfmiller** [comment]
I was not able to reproduce the behavior you see. CanSeek was true during every unit test. I could see that the Position was at the end of the body stream, but the deserializer worked.

Do you know why CanSeek was false for you, but true for me? I'm just curious. Adding "request.EnableRewind();" also worked for me (all tests pasted).

**Comment by brainiac10** [comment]
I know it's after the fact now, but you're right, it's inconsistent depending on the webserver being used, and darned hard to reproduce with unit tests.  In [this thread](https://github.com/aspnet/KestrelHttpServer/issues/1548), they were saying that TestServer doesn't behave like an actual webserver in this regard.

**Comment by andyfmiller** [comment]
It would be an interesting experiment to run the unit tests on a variety of server types. AppVeyor only runs them on Windows.
