### ISSUE TITLE
Help required to integrate learning.com within canvas

### ISSUE THREAD

**Issue by avinashsachdewani** [LtiLibrary/LtiLibrary#7]
I am working on creating an LTI tool for CANVAS, which will be a wrapper over other LTI tools like learning.com. This LTI tool will be coded in C#.Net. I am stuck up in integrating the learning.com to get digital content for the lessons. I am getting zero documentation over the integration of learning.com or how learning.com will be used as LTI provider so that I can consume it in backend. If someone can share some coding examples or provide some good documentation will be really helpful.

**Comment by jeroenhabets** [comment]
Hi, sample code can be found under in Andy's sibling Github project LtiSamples: https://github.com/andyfmiller/LtiSamples
