### ISSUE TITLE
Incompatible extension methods with ASP.NET5

### ISSUE THREAD

**Issue by nikouu** [LtiLibrary/LtiLibrary#8]
Hi Andy,

It's still earlyish days for ASP.NET5 (with MVC6) but the Request object used relies on `System.Web` in the library (for the LTI extensions) whereas the Request object for ASP.NET5 is under `Microsoft.AspNet.Http.HttpRequest`. Specifically, I'm looking at the [HttpRequestBaseExtensions](https://github.com/andyfmiller/LtiLibrary/blob/master/LtiLibrary.AspNet/Extensions/HttpRequestBaseExtensions.cs) class.

Could create the `System.Web` Request object and copy the parameters into it, but I'm trying to work out a cleaner way. A new library with the different type and have that as a Nuget package? Overload the current class? Or something better? ¯_(ツ)_/¯

**Comment by jeroenhabets** [comment]
As a LTI library user and LTI evangelist in the Dutch e-learning market, I am following this issue with extreme interest:

For our own products but also for our partners and even competitors _(yes, we are using LTI to get rid of custom integrations between e-learning systems to create a bigger open market with more value for all our customers)_, it is vital that the library keeps .Net 4.5 support for the foreseeable future.

As .Net 5.0 (4.6) is still in RC, and many companies not upgrading until at least the first .1 release with bugfixes, and even then only when forced to, it will be years before many companies will migrate their production platform to this version.

**Comment by andyfmiller** [comment]
Both LtiLibrary.Core and LtiLibrary.AspNet target .NET Framework 4.5. Microsoft ASP.NET Web API 2 Client 5.0.0 came out in October of 2013.

If you need to target a specific version of .NET or ASP.NET Web API, please download the source and make the appropriate changes.
