### ISSUE TITLE
Test cases fail when current locale is nl-NL

### ISSUE THREAD

**Issue by srijken** [LtiLibrary/LtiLibrary#80]
3 test cases fail when the locale is different from en-US:

LtiLibrary.AspNetCore.Tests.BasicLaunch.ConsumerShould.LaunchATool_WithValidCredentials
LtiLibrary.AspNetCore.Tests.ContentItems.ConsumerShould.LaunchAContentItemSelectionTool_WithValidCredentials

Both fail with this:
```
Message: {
  "launch_presentation_locale": "nl-NL"
}
Expected: True
Actual:   False
```

LtiLibrary.AspNetCore.Tests.Outcomes.v1.OutcomesControllerShould.ReadResult

ReadResult is more concerning than the two above:

```
Message: 5 == 0,5
Expected: True
Actual:   False
```

There's some double parsing in ReadResultAsync that seems to be culture dependent

**Comment by andyfmiller** [comment]
@srijken - See PR #83
