### ISSUE TITLE
Setting CustomParameters property should replace custom parameters.

### ISSUE THREAD

**Issue by andyfmiller** [LtiLibrary/LtiLibrary#92]
```OAuthRequest.CustomParameters``` is a user facing API (it is not used internally by LtiLibrary) that can be confusing.

It was originally created so an application could store the LTI parameters in a single string field within a database. Unfortunately, it also looks like a way to add custom parameters to the ```LtiRequest```. It's not, and this can be confusing.

It would improve LtiLibrary if ``CustomParameters``` was improved to replace the current set of custom parameters and accept a variety of formats.

**Comment by andyfmiller** [comment]
- Moved CustomParameters from OAuthRequest to LtiRequest
- When you ```set``` the ```value```, the current custom parameters are replaced by the custom parameters in the ```value```
- The value string can use any mix of commas, semicolons, ampersands, and newlines to separate custom parameters (e.g. use a <textarea> to collect the custom parameters and set them in one line of code: ```LtiRequest.CustomParameters = textarea.value;```)

**Comment by srijken** [comment]
Looks like this was fixed by #93
