### ISSUE TITLE
Oauth signature generated from http://lti.tools/saltire/tc is different from the Core library

### ISSUE THREAD

**Issue by rri195** [LtiLibrary/LtiLibrary#94]
I am using the http://lti.tools/saltire/tc tool to test, but the Oauth signature the page post to my app is different than the signature generated by LtiLibrary.Core.OAuth.OAuthUtility.GenerateSignature(Request.HttpMethod, Request.Url, Request.Form, clsLtiParams.SharedSecret) 

Also, if the parameter value contains HTML tag, it through exception.

Thanks

Greg

**Comment by andyfmiller** [comment]
Hello Greg,

It sounds like your app is a Tool Provider. In that case I recommend using the ParseLtiRequestAsync extension method to parse the inbound HTTP request into an LtiRequest. Then use the LtiRequest.GenerateSignature method to calculate the signature for comparison. See the [ToolProviderController](https://github.com/andyfmiller/LtiLibrary/blob/master/test/LtiLibrary.AspNetCore.Tests/BasicLaunch/ToolProviderController.cs) in the BasicLaunch tests for an example.

**Comment by rri195** [comment]
But I am not able to install .NETCore and ASPNETCore, it doesn't support Framework 4.5

Could not install package 'LtiLibrary.NetCore 3.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by andyfmiller** [comment]
OK. In that case, let's hop over to the [LtiSamples repo](https://github.com/andyfmiller/LtiSamples) (which uses the source code in [LtiLibrary1.6](https://github.com/andyfmiller/LtiLibrary1.6), which is compatible with .NET 4.5) and use code like [this]:(https://github.com/andyfmiller/LtiSamples/blob/master/SimpleLti/Controllers/ProviderController.cs#L30-L39)

````
                // Parse and validate the request
                var ltiRequest = new LtiRequest(null);
                ltiRequest.ParseRequest(Request);
                ltiRequest.CheckForRequiredLtiParameters();

                if (!ltiRequest.ConsumerKey.Equals("12345"))
                {
                    ViewBag.Message = "Invalid Consumer Key";
                    return View();
                }
````
[LtiLibrary.Core](https://www.nuget.org/packages/LtiLibrary.Core/) and [LtiLibrary.AspNet](https://www.nuget.org/packages/LtiLibrary.AspNet/) 1.6.2 are on NuGet.
