### ISSUE TITLE
Make SHA-256 the default for LTI 1.1 Tool Consumer and LTI 1.1 Tool Provider

### ISSUE THREAD

**Issue by andyfmiller** [LtiLibrary/LtiLibrary#97]
IMS Global issued the following security notice on Feb 5, 2018:

**Security Bulletin
Deprecation notice for SHA-1 Hash Algorithm**
February 2018

IMS Global has decided to deprecate the use of SHA-1 in its standards like Learning Tools Interoperability® (LTI)®  and OneRoster® as the majority of education technology organizations are indicating a desire for use of a more robust encryption algorithm.

A transition period is provided as described below:

**New Certifications** 
All new product certifications after July 1, 2018 must support SHA-256 and we recommend they also support SHA-1 for backward compatibility during the transition period.  The specifications affected by this are:

- LTI 1.1 Tool Consumer
- LTI 1.1 Tool Provider
- OneRoster 1.0 Service Provider - no new certifications to OR 1.0 will be permitted
- OneRoster 1.0 Service Consumer - no new certifications to OR 1.0 will be permitted
- OneRoster 1.1 Service Provider
- OneRoster 1.1 Service Consumer

**Recertifications**
Recertifications after January 1, 2019 must support SHA-256 and we recommend they also support SHA-1 for backward compatibility during the transition period.

- LTI 1.1 Tool Consumer
- LTI 1.1 Tool Provider
- OneRoster 1.0 Service Provider - no re-certifications to OR 1.0 will be permitted
- OneRoster 1.0 Service Consumer - no re-certifications to OR 1.0 will be permitted
- OneRoster 1.1 Service Provider
- OneRoster 1.1 Service Consumer

**Final Deprecation**
Effective January 1, 2020 SHA-1 must not be used and will no longer be certified.

IMS is publishing an ecosystem-wide security framework based upon OAuth 2 which is implemented in its latest released standards such as [LTI Advantage](https://www.imsglobal.org/lti-advantage-overview).

**Comment by srijken** [comment]
What's the plan to do this? I think it's not just a matter of changing the default value to SHA256, because that would be a major breaking change. Question is, what will be the correct way to handle this?

**Comment by andyfmiller** [comment]
I'm thinking of taking my cues from IMS. I'd like to see what they do in LTI 1.3.

**Comment by jeroenhabets** [comment]
Hi @andyfmiller, @srijken, by now [IMS's deprecation notice](https://www.imsglobal.org/lti-security-announcement-and-deprecation-schedule) is almost 4 years old and all LTI 1.0/1.1x/1.2/2.0 are unsupported for more than half a year so I've taken the liberty to close this old ticket. Cheers, Jeroen
