### ISSUE TITLE
Preferred approach for integrating LtiLibrary into OAuth flow in ASP.NET MVC Core 2.0?

### ISSUE THREAD

**Issue by hempels** [LtiLibrary/LtiLibrary#99]
There is some startup code in LtiSamples that appears to make a call to an app.UseLtiAuthentication extension, however, no such extension seems to exist in this repo or in the samples repo.

Further, with ASP.NET Core 2.0 that is no longer the pattern they employ. Instead, authentication is configured in ConfigureServices via AuthenticationBuilder extensions.

Is there guidance available or work in progress on enabling a simple method for hooking up LTI Authentication for .NET Core or is that something we'll need to either roll our own or do the auth handling directly within each action method (as seen in LtiSamples/SimpleLti)?

I would be happy to contribute anything we come up with back to the project, but I'm having trouble following the current state of things and figuring out the intended direction, so I don't feel confident I would be able to make a useful contribution without some guidance.

**Comment by andyfmiller** [comment]
After writing https://github.com/andyfmiller/LtiLibrary.Owin and publishing https://www.nuget.org/packages/LtiLibrary.Owin.Security.Lti, I did not pay much attention to it. It looks like few others did either.

LtiSamples has been updated many times and I stripped out the LTI authentication stuff because Microsoft was was changing it too fast for me to keep up.

I don't think there is any particular direction at this point.

**Comment by jeroenhabets** [comment]
Hi @hempels, now more than 3 years later Microsoft has moved on to, .Net Core 3.1 and, .Net 5/6 and this project to sibling repo [LtiAdvantage](../../LtiAdvantage) as [IMS has deprecated LTI < 1.3](https://www.imsglobal.org/node/183196) and the LtiAdvantage repo [supports .Net Core](https://github.com/LtiLibrary/LtiAdvantage/tree/master/src/LtiAdvantage.AspNetCore), I've now taken the liberty to close your ticket.

N.B. This LTILibrary here should basically be considered deprecated. It is still useful to support the few Tools/Platforms that have not migrated yet but [LTI Advantage](../../LtiAdvantage) (LTI 1.3) is the way forward.
